package com.mycompany.sistemacontable.servicio;
import com.mycompany.sistemacontable.Conexion;import java.math.*;import java.sql.*;import java.util.*;
public class AlertasService {
 public record Alerta(String titulo,String detalle){} public record Resumen(String ventas,String inventario,String utilidad,String balance){} public record DatoGrafica(String etiqueta,double valor){}
 private int periodo(){try{return new PeriodoService().obtenerPeriodoActivo().getIdPeriodo();}catch(Exception e){return -1;}}
 public List<Alerta> obtener(){List<Alerta>a=new ArrayList<>();int id=periodo();try(Connection c=Conexion.conectar()){
  int d=intQ(c,"SELECT COUNT(*) FROM (SELECT a.id_asiento FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento WHERE a.estado<>'ANULADO' AND a.id_periodo="+id+" GROUP BY a.id_asiento HAVING ABS(SUM(d.debe)-SUM(d.haber))>0.009)x");
  int p=intQ(c,"SELECT COUNT(*) FROM asientos_contables WHERE estado='BORRADOR' AND id_periodo="+id);int dup=intQ(c,"SELECT COUNT(*) FROM (SELECT fecha,concepto,COUNT(*) n FROM asientos_contables WHERE estado<>'ANULADO' AND id_periodo="+id+" GROUP BY fecha,concepto HAVING COUNT(*)>1)x");
  BigDecimal cob=decQ(c,"SELECT COALESCE(SUM(CASE WHEN cc.naturaleza='DEUDORA' THEN d.debe-d.haber ELSE d.haber-d.debe END),0) FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo="+id+" AND cc.rol_reporte='CUENTAS_COBRAR'");
  a.add(new Alerta(d+" partidas descuadradas",d==0?"Sin diferencias detectadas":"Revisar Debe y Haber"));a.add(new Alerta(p+" documentos pendientes",p==0?"No hay borradores":"Pendientes de contabilizar/aprobar"));a.add(new Alerta(dup+" posibles duplicados",dup==0?"Sin duplicados evidentes":"Misma fecha y concepto"));a.add(new Alerta(moneda(cob)+" pendiente de cobro","Saldo de cuentas por cobrar"));
 }catch(SQLException e){throw new RuntimeException(e);}return a;}
 public Resumen obtenerResumen(){int id=periodo();try(Connection c=Conexion.conectar()){BigDecimal v=decQ(c,"SELECT COALESCE(SUM(d.haber-d.debe),0) FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo="+id+" AND cc.rol_reporte IN('VENTAS','DEVOLUCION_VENTAS')");BigDecimal inv=decQ(c,"SELECT COALESCE(SUM(d.debe-d.haber),0) FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo="+id+" AND cc.rol_reporte='INVENTARIO'");BigDecimal ing=decQ(c,"SELECT COALESCE(SUM(d.haber-d.debe),0) FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo="+id+" AND cc.tipo='INGRESO'");BigDecimal gas=decQ(c,"SELECT COALESCE(SUM(d.debe-d.haber),0) FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo="+id+" AND cc.tipo IN('COSTO','GASTO')");int desc=intQ(c,"SELECT COUNT(*) FROM (SELECT a.id_asiento FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento WHERE a.estado<>'ANULADO' AND a.id_periodo="+id+" GROUP BY a.id_asiento HAVING ABS(SUM(d.debe)-SUM(d.haber))>0.009)x");return new Resumen(moneda(v),moneda(inv),moneda(ing.subtract(gas)),desc==0?"Cuadrado":"Revisar");}catch(SQLException e){return new Resumen("$0.00","$0.00","$0.00","Pendiente");}}
 public List<DatoGrafica> ventasPorMes(){int id=periodo();List<DatoGrafica>x=new ArrayList<>();String q="SELECT DATE_FORMAT(a.fecha,'%b') mes,MONTH(a.fecha) n,COALESCE(SUM(d.haber-d.debe),0) total FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo=? AND cc.rol_reporte IN('VENTAS','DEVOLUCION_VENTAS') GROUP BY MONTH(a.fecha),DATE_FORMAT(a.fecha,'%b') ORDER BY n";try(Connection c=Conexion.conectar();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,id);try(ResultSet r=ps.executeQuery()){while(r.next())x.add(new DatoGrafica(r.getString(1),r.getDouble(3)));}}catch(SQLException ignored){}return x;}
 public List<DatoGrafica> gastosPorTipo(){int id=periodo();List<DatoGrafica>x=new ArrayList<>();String q="SELECT cc.tipo,COALESCE(SUM(d.debe-d.haber),0) total FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo=? AND cc.tipo IN('COSTO','GASTO') GROUP BY cc.tipo ORDER BY cc.tipo";try(Connection c=Conexion.conectar();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,id);try(ResultSet r=ps.executeQuery()){while(r.next())x.add(new DatoGrafica(r.getString(1),r.getDouble(2)));}}catch(SQLException ignored){}return x;}

 public List<DatoGrafica> comprasPorMes(){int id=periodo();List<DatoGrafica>x=new ArrayList<>();String q="SELECT DATE_FORMAT(a.fecha,'%b') mes,MONTH(a.fecha) n,COALESCE(SUM(d.debe-d.haber),0) total FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo=? AND cc.rol_reporte IN('COMPRAS','DEVOLUCION_COMPRAS') GROUP BY MONTH(a.fecha),DATE_FORMAT(a.fecha,'%b') ORDER BY n";try(Connection c=Conexion.conectar();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,id);try(ResultSet r=ps.executeQuery()){while(r.next())x.add(new DatoGrafica(r.getString(1),Math.max(0,r.getDouble(3))));}}catch(SQLException ignored){}return x;}
 public List<DatoGrafica> estructuraContable(){int id=periodo();List<DatoGrafica>x=new ArrayList<>();String q="SELECT cc.tipo,COALESCE(SUM(CASE WHEN cc.naturaleza='DEUDORA' THEN d.debe-d.haber ELSE d.haber-d.debe END),0) total FROM asientos_contables a JOIN detalle_asientos d ON d.id_asiento=a.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.estado='CONTABILIZADO' AND a.id_periodo=? AND cc.tipo IN('ACTIVO','PASIVO','PATRIMONIO') GROUP BY cc.tipo ORDER BY FIELD(cc.tipo,'ACTIVO','PASIVO','PATRIMONIO')";try(Connection c=Conexion.conectar();PreparedStatement ps=c.prepareStatement(q)){ps.setInt(1,id);try(ResultSet r=ps.executeQuery()){while(r.next())x.add(new DatoGrafica(r.getString(1),Math.max(0,r.getDouble(2))));}}catch(SQLException ignored){}return x;}
 private String moneda(BigDecimal v){return "$"+v.setScale(2,RoundingMode.HALF_UP);}private int intQ(Connection c,String q)throws SQLException{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(q)){r.next();return r.getInt(1);}}private BigDecimal decQ(Connection c,String q)throws SQLException{try(Statement s=c.createStatement();ResultSet r=s.executeQuery(q)){r.next();BigDecimal v=r.getBigDecimal(1);return v==null?BigDecimal.ZERO:v;}}
}
