package com.mycompany.sistemacontable.servicio;
import com.mycompany.sistemacontable.Conexion; import com.mycompany.sistemacontable.dao.*; import com.mycompany.sistemacontable.modelo.*;
import java.io.*; import java.nio.charset.StandardCharsets; import java.math.*; import java.sql.*; import java.time.*; import java.time.format.*; import java.util.*; import org.apache.poi.ss.usermodel.*;
public class ConciliacionService {
 private final ConciliacionDAO dao=new ConciliacionDAO();
 public int importar(File f){if(!SesionUsuario.puedeRegistrarOperaciones())throw new SecurityException("No tiene permiso para conciliar.");PeriodoContable p=new PeriodoContableDAO().obtenerPeriodoAbierto();if(p==null)throw new IllegalStateException("No hay período abierto.");List<MovimientoBancario> mov=leer(f);if(mov.isEmpty())throw new IllegalArgumentException("El archivo no contiene movimientos válidos.");try(Connection cn=Conexion.conectar()){cn.setAutoCommit(false);Integer uid=SesionUsuario.getUsuarioActual()==null?null:SesionUsuario.getUsuarioActual().getIdUsuario();long carga=dao.crearCarga(p.getIdPeriodo(),uid,f.getName(),cn);for(MovimientoBancario m:mov){var match=dao.buscarMejor(p.getIdPeriodo(),m.getFecha(),m.getMonto(),m.getDescripcion(),cn);if(match!=null){m.setIdDetalleAsiento(match.idDetalle());m.setPuntaje(match.puntaje());m.setEstado(match.puntaje()>=95?"COINCIDENTE":"POSIBLE_COINCIDENCIA");}else m.setEstado("SIN_CONCILIAR");dao.insertar(carga,m,cn);}cn.commit();return mov.size();}catch(Exception e){throw new RuntimeException("No se pudo importar: "+e.getMessage(),e);}}
 public List<MovimientoBancario> listar(){return dao.listarUltima();} public void decidir(long id,boolean conciliar){dao.decidir(id,conciliar?"CONCILIADO_MANUAL":"DESCARTADO");}
 private List<MovimientoBancario> leer(File f){String n=f.getName().toLowerCase();try{return n.endsWith(".csv")?leerCsv(f):leerExcel(f);}catch(Exception e){throw new IllegalArgumentException("No se pudo leer el archivo. Use CSV/XLS/XLSX con columnas Fecha, Descripción y Monto (o Débito/Crédito). "+e.getMessage(),e);}}
 private List<MovimientoBancario> leerCsv(File f)throws Exception{List<MovimientoBancario> out=new ArrayList<>();try(BufferedReader br=new BufferedReader(new InputStreamReader(new FileInputStream(f),StandardCharsets.UTF_8))){String h=br.readLine();if(h==null)return out;char sep=h.contains(";")?';':',';String[] hs=h.split(java.util.regex.Pattern.quote(String.valueOf(sep)),-1);Map<String,Integer> ix=indices(hs);String l;while((l=br.readLine())!=null){String[] v=l.split(java.util.regex.Pattern.quote(String.valueOf(sep)),-1);MovimientoBancario m=desdeValores(ix,i->i<v.length?v[i].replace("\"","").trim():"");if(m!=null)out.add(m);}}return out;}
 private List<MovimientoBancario> leerExcel(File f)throws Exception{List<MovimientoBancario> out=new ArrayList<>();try(InputStream in=new FileInputStream(f);Workbook wb=WorkbookFactory.create(in)){Sheet sh=wb.getSheetAt(0);if(sh.getPhysicalNumberOfRows()<2)return out;DataFormatter df=new DataFormatter();Row hr=sh.getRow(sh.getFirstRowNum());String[] hs=new String[hr.getLastCellNum()];for(int i=0;i<hs.length;i++)hs[i]=df.formatCellValue(hr.getCell(i));Map<String,Integer> ix=indices(hs);for(int r=hr.getRowNum()+1;r<=sh.getLastRowNum();r++){Row row=sh.getRow(r);if(row==null)continue;MovimientoBancario m=desdeValores(ix,i->df.formatCellValue(row.getCell(i)).trim());if(m!=null)out.add(m);}}return out;}
 private interface Val{String get(int i);} private MovimientoBancario desdeValores(Map<String,Integer>x,Val v){Integer fi=pick(x,"fecha","date"),di=pick(x,"descripcion","descripción","concepto","detalle"),ri=pick(x,"referencia","ref"),mi=pick(x,"monto","importe","amount"),de=pick(x,"debito","débito","cargo"),cr=pick(x,"credito","crédito","abono");if(fi==null||(mi==null&&de==null&&cr==null))return null;String fs=v.get(fi);if(fs.isBlank())return null;MovimientoBancario m=new MovimientoBancario();m.setFecha(fecha(fs));m.setDescripcion(di==null?"":v.get(di));m.setReferencia(ri==null?"":v.get(ri));BigDecimal val=mi!=null?numero(v.get(mi)):BigDecimal.ZERO;if(mi==null){BigDecimal d=de==null?BigDecimal.ZERO:numero(v.get(de));BigDecimal c=cr==null?BigDecimal.ZERO:numero(v.get(cr));val=c.signum()!=0?c:d.negate();}m.setMonto(val.setScale(2,RoundingMode.HALF_UP));return m;}
 private Map<String,Integer> indices(String[]h){Map<String,Integer>x=new HashMap<>();for(int i=0;i<h.length;i++)x.put(h[i].replace("\ufeff","").trim().toLowerCase(),i);return x;} private Integer pick(Map<String,Integer>x,String...k){for(String s:k)if(x.containsKey(s))return x.get(s);return null;}
 private BigDecimal numero(String s){if(s==null||s.isBlank())return BigDecimal.ZERO;s=s.replace("$","").replace(" ","");if(s.contains(",")&&s.contains("."))s=s.replace(",","");else if(s.contains(","))s=s.replace(',','.');return new BigDecimal(s);}
 private LocalDate fecha(String s){s=s.trim();for(String p:new String[]{"yyyy-MM-dd","dd/MM/yyyy","MM/dd/yyyy","dd-MM-yyyy"})try{return LocalDate.parse(s,DateTimeFormatter.ofPattern(p));}catch(Exception ignored){}try{return LocalDate.of(1899,12,30).plusDays((long)Double.parseDouble(s));}catch(Exception e){throw new IllegalArgumentException("Fecha inválida: "+s);}}
}
