package com.mycompany.sistemacontable.dao;
import com.mycompany.sistemacontable.Conexion; import com.mycompany.sistemacontable.modelo.MovimientoBancario;
import java.sql.*; import java.util.*; import java.math.BigDecimal; import java.time.LocalDate;
public class ConciliacionDAO {
 public long crearCarga(int periodo,Integer usuario,String archivo,Connection cn)throws SQLException{try(PreparedStatement p=cn.prepareStatement("INSERT INTO conciliaciones_bancarias(id_periodo,id_usuario,nombre_archivo) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setInt(1,periodo);if(usuario==null)p.setNull(2,Types.INTEGER);else p.setInt(2,usuario);p.setString(3,archivo);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();return r.getLong(1);}}}
 public void insertar(long carga,MovimientoBancario m,Connection cn)throws SQLException{try(PreparedStatement p=cn.prepareStatement("INSERT INTO movimientos_bancarios(id_conciliacion,fecha,descripcion,referencia,monto,estado,id_detalle_asiento,puntaje) VALUES(?,?,?,?,?,?,?,?)")){p.setLong(1,carga);p.setDate(2,java.sql.Date.valueOf(m.getFecha()));p.setString(3,m.getDescripcion());p.setString(4,m.getReferencia());p.setBigDecimal(5,m.getMonto());p.setString(6,m.getEstado());if(m.getIdDetalleAsiento()==null)p.setNull(7,Types.INTEGER);else p.setInt(7,m.getIdDetalleAsiento());p.setInt(8,m.getPuntaje());p.executeUpdate();}}
 public List<MovimientoBancario> listarUltima(){List<MovimientoBancario>x=new ArrayList<>();String q="SELECT mb.*, CONCAT('Asiento ',a.numero_asiento,' - ',a.concepto) sug FROM movimientos_bancarios mb JOIN conciliaciones_bancarias c ON c.id_conciliacion=mb.id_conciliacion LEFT JOIN detalle_asientos d ON d.id_detalle=mb.id_detalle_asiento LEFT JOIN asientos_contables a ON a.id_asiento=d.id_asiento WHERE mb.id_conciliacion=(SELECT MAX(id_conciliacion) FROM conciliaciones_bancarias) ORDER BY mb.fecha,mb.id_movimiento";try(Connection c=Conexion.conectar();PreparedStatement p=c.prepareStatement(q);ResultSet r=p.executeQuery()){while(r.next()){MovimientoBancario m=new MovimientoBancario();m.setIdMovimiento(r.getLong("id_movimiento"));m.setFecha(r.getDate("fecha").toLocalDate());m.setDescripcion(r.getString("descripcion"));m.setReferencia(r.getString("referencia"));m.setMonto(r.getBigDecimal("monto"));m.setEstado(r.getString("estado"));int id=r.getInt("id_detalle_asiento");m.setIdDetalleAsiento(r.wasNull()?null:id);m.setPuntaje(r.getInt("puntaje"));m.setAsientoSugerido(r.getString("sug"));x.add(m);}}catch(SQLException e){throw new RuntimeException(e);}return x;}
 public void decidir(long id,String estado){String q="UPDATE movimientos_bancarios SET estado=?,fecha_decision=NOW(),id_usuario_decision=? WHERE id_movimiento=?";try(Connection c=Conexion.conectar();PreparedStatement p=c.prepareStatement(q)){p.setString(1,estado);var u=com.mycompany.sistemacontable.servicio.SesionUsuario.getUsuarioActual();if(u==null)p.setNull(2,Types.INTEGER);else p.setInt(2,u.getIdUsuario());p.setLong(3,id);p.executeUpdate();}catch(SQLException e){throw new RuntimeException(e);}}
 public Match buscarMejor(int periodo,LocalDate fecha,BigDecimal monto,String desc,Connection cn)throws SQLException{String q="SELECT d.id_detalle,a.numero_asiento,a.fecha,a.concepto,d.descripcion,d.debe,d.haber FROM detalle_asientos d JOIN asientos_contables a ON a.id_asiento=d.id_asiento JOIN catalogo_cuentas cc ON cc.id_cuenta=d.id_cuenta WHERE a.id_periodo=? AND a.estado='CONTABILIZADO' AND (UPPER(cc.nombre) LIKE '%BANCO%' OR cc.id_cuenta_padre IN (SELECT id_cuenta FROM catalogo_cuentas WHERE rol_reporte='EFECTIVO')) AND ABS(DATEDIFF(a.fecha,?))<=5 AND GREATEST(d.debe,d.haber)=? AND d.id_detalle NOT IN (SELECT id_detalle_asiento FROM movimientos_bancarios WHERE id_detalle_asiento IS NOT NULL AND estado IN('COINCIDENTE','CONCILIADO_MANUAL')) ORDER BY ABS(DATEDIFF(a.fecha,?)) LIMIT 1";try(PreparedStatement p=cn.prepareStatement(q)){p.setInt(1,periodo);p.setDate(2,java.sql.Date.valueOf(fecha));p.setBigDecimal(3,monto.abs());p.setDate(4,java.sql.Date.valueOf(fecha));try(ResultSet r=p.executeQuery()){if(r.next()){int dias=Math.abs((int)java.time.temporal.ChronoUnit.DAYS.between(fecha,r.getDate("fecha").toLocalDate()));String texto=(r.getString("concepto")+" "+Objects.toString(r.getString("descripcion"),"")).toLowerCase();int score=dias==0?100:(dias<=2?85:70);if(desc!=null&&!desc.isBlank()){for(String w:desc.toLowerCase().split("\\s+"))if(w.length()>3&&texto.contains(w)){score=Math.min(100,score+5);break;}}return new Match(r.getInt("id_detalle"),score,"Asiento "+r.getInt("numero_asiento")+" - "+r.getString("concepto"));}}}return null;}
 public record Match(int idDetalle,int puntaje,String texto){}
}
